"""Script to generate keywords module"""

from pathlib import Path

from pydicom.datadict import (
    DicomDictionary,
    dictionary_keyword,
)

_PKG_DIRECTORY = Path(__file__).parents[1]
KEYWORDS_FILE_NAME = _PKG_DIRECTORY.joinpath("utilities", "keywords.py")


def run():
    """Writes module file"""
    with open(KEYWORDS_FILE_NAME, "w") as f:
        f.write(
            '"""DICOM keywords module auto-generated by '
            f'{Path(__file__).name}"""\n'
        )
        f.write("# flake8: noqa\n")
        f.write("# pylint: disable-all\n\n")

        for tag in DicomDictionary:
            keyword = dictionary_keyword(tag)
            if keyword:
                f.write(f'{keyword} = "{keyword}"\n')


if __name__ == "__main__":
    run()
